### ISSUE TITLE
phonegap build problem?

### ISSUE THREAD

**Issue by hsyn** [monday-consulting/ContactChooser#1]
"Right now, you cannot submit your own plugins to PhoneGap Build and have them included on our system. We are working on the infrastructure changes to allow this support."

Does this mean that i can not use this plugin to create an IOS app even though it works smoothly on my development machine?
ref: https://build.phonegap.com/docs/plugins

**Comment by malde** [comment]
It seems like there is currently no way to use it with PhoneGap Build.
We are not using Build, so there are currently no plans to submit the plugin as a contribution.

**Comment by hsyn** [comment]
Thanks for reply, but, If you are not using PhoneGap Build, how do you send your app to AppStore ?

**Comment by malde** [comment]
The "old-fashioned" way. By building the native app and submitting it. 
ref: http://cordova.apache.org/docs/en/2.5.0/guide_getting-started_ios_index.md.html#Getting%20Started%20with%20iOS

**Comment by hsyn** [comment]
thanks for the plugin and heads up, it helped :)
