### ISSUE TITLE
iOS, picker displayed, but no OK button?

### ISSUE THREAD

**Issue by peebles** [monday-consulting/ContactChooser#12]
The picker comes up and appears to be fully functional, except I cannot actually pick a contact.  There is no obvious OK button or anything else.  All I can do is cancel.  

I am using the google Chrome App flow to create a mobile app for iPhone.

**Comment by malde** [comment]
As far as I understand, you have to select an email or phone number. Isn't this the usual behavior on an iPhone? (sorry, haven't used this for a while)

**Comment by pthor** [comment]
Clicking on the email address of a contact seems to work as expected, but clicking on the phone number actually calls the contact, instead of passing the contact back into the app.

**Comment by ollide** [comment]
I've [adjusted](https://github.com/monday-consulting/ContactChooser/commit/2002141764f8d05358a38de70564ddbb48cd8f39) the plugin's behavior. Selecting an email address returns the clicked address, the contact's name and, if available, the first phone number (index 0). This is pretty much the same as before. A click on a phone number will now behave the same: the plugin returns the selected phone number, the contact's name and, if available, the first email address (index 0).
