### ISSUE TITLE
Broken on ios8

### ISSUE THREAD

**Issue by peterholcomb** [monday-consulting/ContactChooser#13]
I believe this no longer works on ios8.  When you bring up the contact picker and choose a contact, it now starts an email to that user instead of returning to the app.  This was working great on ios7 until I upgraded this week to ios8.

**Comment by peterholcomb** [comment]
I was able to fix it by adding the following to ContactPicker.m
- (void)peoplePickerNavigationController:(ABPeoplePickerNavigationController *)peoplePicker
                       didSelectPerson:(ABRecordRef)person
                              property:(ABPropertyID)property
                            identifier:(ABMultiValueIdentifier)identifier
  {
  
  [self peoplePickerNavigationController:peoplePicker shouldContinueAfterSelectingPerson:person property:property identifier:identifier];
  }

**Comment by agarrharr** [comment]
Thanks. If you could submit a pull request, that would be great.

**Comment by ollide** [comment]
Thanks a lot! Your provided solution works and has been [included](https://github.com/monday-consulting/ContactChooser/commit/c78241dba6ece01fde5719112eeb6841476d94ec) to ensure iOS8 support.

I've also got rid of some [deprecation warnings](https://github.com/monday-consulting/ContactChooser/commit/36775811f786efc7f192d19a5bf06c9f2664b239) and switched to the new [result API](https://github.com/monday-consulting/ContactChooser/commit/7443348621f581d910d226d442e8dcabb5ccc35f) to guarantee support for the upcoming Cordova 4.0 release.
