### ISSUE TITLE
Cordova 3.x compatibility on iOS

### ISSUE THREAD

**Issue by fkfhain** [monday-consulting/ContactChooser#2]
Hi,

it seems that the iOS plugin method signature has changed with the introduction of cordova 3.0.

Before that the signature

```

 - (void)myMethod:(NSMutableArray*)arguments withDict:(NSMutableDictionary*)options;
```

was deprecated but usable. 
http://cordova.apache.org/docs/en/2.9.0/guide_plugin-development_ios_index.md.html#Developing%20a%20Plugin%20on%20iOS

That has changed with cordova 3.x. The deprecated signature disappeared. 
http://cordova.apache.org/docs/en/3.1.0/guide_platforms_ios_plugin.md.html#iOS%20Plugins

I don't have any clue about iOS development. Any chance you may fix this to make your excellent plugin functional for current cordova versions?

Thanks,
fkfhain

**Comment by ollide** [comment]
Hi fkfhain,

I've just created a cordova-3.x branch which should be compliant with the new plugin interface.
The provided minimal example works on iOS 7 Simulator and Nexus 4 device.

Let me know if you encounter any problems!
