### ISSUE TITLE
ABMultiValueIdentifier index is wrong if contacts >=4

### ISSUE THREAD

**Issue by daxiang28** [monday-consulting/ContactChooser#7]
If there are 4 or more emails in a contact's card, the index always defaults to 2 . Also the first email selected defaults to 2. Is the ABMultiValueIdentifier index being reported improperly? 

Steve

**Comment by ollide** [comment]
I tried the current version of the plugin on iOS8 (iPhone 5) and iOS7 (iPhone 4) with 4 and more email addresses and could not reproduce the issue. Feel free to reopen this, if you still encounter a false index.
